### ISSUE TITLE
TypeError: WebSocket.__init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'

### ISSUE THREAD

**Issue by e-lunev** [luanon404/Quizizz-Cheat#1]
Traceback (most recent call last):
  File "C:\Users\Jenya\Desktop\qwizizz.py", line 253, in <module>
    room_data = quizizz.get_room_data(username, room_hash, sid)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jenya\Desktop\qwizizz.py", line 111, in get_room_data
    ws = websocket.WebSocket()
         ^^^^^^^^^^^^^^^^^^^^^
TypeError: WebSocket.__init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'

**Comment by e-lunev** [comment]
pip install websocket-client

**Comment by Manerva** [comment]
pip uninstall websocket
pip install websocket-client
